function build()
    compiler.build.standaloneWindowsApplication( ...
        "./main.m", ...
        ExecutableName="Atie", ...
        AdditionalFiles="../vite/dist/", ...
        OutputDir="./dist/", ...
        ObfuscateArchive=true, ...
        Verbose=true);
end
